### ISSUE TITLE
similarities/differences with react-redux-firebase

### ISSUE THREAD

**Issue by prescottprue** [manuelJung/redux-firebase-user#1]
Love the idea!

I'm one of the the authors of [react-redux-firebase](http://react-redux-firebase.com/) (please forgive the plug)

Any interest on working similar compatibility into `react-redux-firebase` or merging? The plans for `v2.0.0` are still open for input and would love to hear your input.

User/Account stuff is handled currently, but it is not within it's own "user" reducer as it seems that you have done here. Other than that, seems that we are following relatively similar logic.

Side Note: I really like what you have done with the selectors and paying attention to modularity

**Comment by manuelJung** [comment]
thanks :)

the main purpose of this lib is to show a way how a piece of the application logic can be handled in it's own module without any connection to the rest of the application. Therefore I am defining a interface of how such a module can interact with the application (via hocs and [updaters](https://blog.javascripting.com/2016/02/02/encapsulation-in-redux/); or on a lower level via selectors and actions). In the end I hopefully created a concept that defines how to create a reusable react-redux module and is portable to any piece of the application logic.

Although there is currently a really smart state of the art ([ducks](https://github.com/erikras/ducks-modular-redux)), it does not scale for large modules and does not define how to interact with the the react side.

To your question: yes I would like to contribute :) This would be great for verifying some of the ideas
